### ISSUE TITLE
Why tho?

### ISSUE THREAD

**Issue by Fischsalat** [cledtz/SDKS#1]
Come on, it's a free fucking dumper, I made it to be open source, and there are no restrictions on sharing the sdk what so ever. 

I'm just wondering why you decided to remove credits?

**Comment by cledtz** [comment]
because its ugly, there is literally a readme linking your project.

**Comment by Fischsalat** [comment]
![image](https://github.com/cledtz/SDKS/assets/64608145/5bf5fef5-e911-4958-a36f-70502959185c)
![image](https://github.com/cledtz/SDKS/assets/64608145/8f25898a-b080-4c2c-b65f-e659802247ae)

**Comment by Fischsalat** [comment]
chill
